const jokesArray = [
    "RIP boiling water, you will be mist.",
    "I once wrote a song about a tortilla, but it's more of a wrap.",
    "A witch's vehicle goes brrroom brrroom.",
    "The waiter asked if I wanted a box for my leftovers, but I told him I’m not into fighting.",
    "If you see a crime at an Apple store, are you an iWitness?",
    "If the early bird catches the worm, I'll sleep in until there are pancakes.",
    "The wedding was so beautiful, even the cake was in tiers.",
    "I used to be able to play the piano by ear, but now I have to use my hands.",
    "Did Noah include termites on the ark?",
    "I used to hate facial hair, but it grew on me.",
    "Keep the dream alive, and hit the snooze button.",
    "I tell dad jokes but I have no kids. I’m a faux pa.",
    "I'm afraid of speed bumps, but I am slowly getting over it.",
    "Some people think prison is one word, but to robbers, it's the whole sentence.",
    "I used to be addicted to soap, but I’m clean now.",
    "Spring is here I got so excited I wet my plants.",
    "I poured root beer in a square glass. Now I just have beer.",
    "I had a dream about being a muffler. I woke up exhausted.",
    "Talk is cheap until you talk to a lawyer.",
    "A pony with a cough is just a little horse.",
    "It takes guts to be an organ donor.",
    "To whoever stole my copy of Microsoft Office, I will find you. You have my Word!",
    "How do celebrities stay cool? They have many fans.",
    "What's Forrest Gump's Facebook password? 1forest1.",
    "What did the fisherman say to the magician? Pick a cod, any cod.",
    "What do you call a fake noodle? An impasta.",
    "How do you organize a space party? You planet.",
    "Did you know that milk is the fastest liquid on earth? It's pasteurized before you can even see it.",
    "What does a baby computer call his father? Data.",
    "Why can't a leopard hide? Because he's always spotted.",
    "How many tickles does it take to make an octopus laugh? 10 tickles.",
    "What do you call an illegally parked frog? Toad.",
    "Why are spiders so smart? They can find everything on the web.",
    "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
    "Did you hear about the circus fire? It was in tents.",
    "Can February March? No, but April May.",
    "How do lawyers say goodbye? We'll be suing ya.",
    "Wanna hear a joke about paper? Never mind—it's tearable.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "I could tell a joke about pizza, but it's a little cheesy.",
    "Every time I take my dog to the park, the ducks try to bite him. That's what I get for buying a pure bread dog.",
    "What is a funny mountain called? Hill-arious.",
    "I wouldn't buy anything with velcro. It's a total rip-off.",
    "What time did the man go to the dentist? Tooth hurt-y.",
    "What kind of egg did the evil chicken lay? A deviled egg.",
    "Which is faster, hot or cold? Hot, because you can catch a cold.",
    "I made a pencil with two erasers. It was pointless.",
    "How does a bee brush its hair? It uses a honeycomb.",
    "How do you make a Kleenex dance? Put a little boogie in it.",
    "What do you get from a pampered cow? Spoiled milk.",
    "Where do baby cats learn to swim? The kitty pool.",
    "How can you tell it's a dogwood tree? From the bark.",
    "What sound does the engine of a witch’s vehicle make? Broooom broooom.",
    "What do you call a fish wearing a bow tie? Sofishticated.",
    "What bone will a dog never eat? A trombone.",
    "Sundays are always a little sad, but the day before is a sadder day.",
    "Where do you learn to make a banana split? Sundae school.",
    "How do you row a canoe filled with puppies? Bring out the doggy paddle.",
    "Why is cold water so insecure? Because it's never called hot.",
    "I don't trust stairs. They're always up to something.",
    "Why do bees have sticky hair? Because they use a honeycomb.",
    "What did Tennessee? The same thing as Arkansas.",
    "Why is it bad to iron your four-leaf clover? Because you shouldn't press your luck.",
    "What rock group has four men who don't sing? Mount Rushmore.",
    "Where do pirates buy hooks? The second hand store.",
    "Why didn’t the skeleton go on the rollercoaster? It didn’t have the guts.",
    "Why did the birds attack the dog? He was pure bread.",
    "What did the nose tell the finger? Stop picking on me.",
    "What do you call a sick lemon? Lemon-aid.",
    "What gets wetter the more it dries? A towel.",
    "What do you call a toothless bear? A gummy bear.",
    "Why can't your hand be 12 inches long? Because then it would be a foot.",
    "What has four wheels and flies? A garbage truck.",
    "Why are pigs so bad at sports? Because they always hog the ball.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "How do moths swim? Using the butterfly stroke.",
    "What's an astronaut's favorite part of a computer? The space bar.",
    "I hit in the head with a soda can. Thankfully it was a soft drink.",
    "What's the name of my cheese? Nacho cheese.",
    "Knock, knock. Who's there? Cows go. Cows go who? No, cows go moo.",
    "What's the loudest pet you can own? A trumpet.",
    "What did the buffalo say to his son when he dropped him off at school? Bison.",
    "What does a pampered cow give? Spoiled milk.",
    "I made a whopping six figures last year. I also was fired from the toy factory for being too slow.",
    "Knock, knock. Who's there? A little old lady. A little old lady who? Hey, you can yodel!",
    "Why did the teddy bear skip dessert? She was stuffed.",
    "What did the left eye say to the right? Something smells between us.",
    "What do you call a singing laptop? A Dell.",
    "What’s it called when a snowman throws a tantrum? A meltdown.",
    "What did the scarecrow win an award for? He was outstanding in his field.",
    "I don’t know much about the best things in Switzerland, but their flag is a big plus.",
    "I used to hate facial hair, but then it grew on me.",
    "I invented a pencil with an eraser on each end. There’s no point to it.",
    "What do you call it when Batman skips church? Christian Bale.",
    "Did you hear about the man who fell into an upholstery machine? He's fully recovered.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "What’s the astronaut's favorite part of a computer? The spacebar.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Did you hear about the power outlet who got into a fight with a power cord? He thought he could socket to him.",
    "Why are elevator jokes so good? They work on so many levels.",
    "Why did the nurse need a red pen? In case she needed to draw blood.",
    "Do you know the story about the chicken that crossed the border? Me neither, I couldn't follow it.",
    "How can a leopard change his spots? By moving.",
    "Don't trust atoms. They make up everything.",
    "What's an astronaut's favorite part of a computer? The space bar.",
    "I'm afraid of the calendar. Its days are numbered.",
    "Two guys walked into a bar. The third guy ducked.",
    "My wife said I should do lunges to stay in shape. That would be a big step forward.",
    "What did the zero say to the eight? That belt looks good on you.",
    "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
    "How do trees get online? They just log on.",
    "How does the moon cut his hair? Eclipse it.",
    "Air used to be free at the gas station. Now it's $1.50. You know why? Inflation.",
    "When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.",
    "I'll call you later. Don't call me later, call me Dad!",
    "When does a joke become a dad joke? When it becomes apparent.",
    "Which bear is the most condescending? A pan-duh.",
    "What kind of drink can be bitter and sweet? Reali-tea.",
    "Why do dads take an extra pair of socks when they're golfing? In case they get a hole in one!",
    "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
    "Where do fruits go on vacation? Pear-is.",
    "Why do melons have weddings? Because they cantaloupe.",
    "What kind of cars do eggs drive? Yolkswagens.",
    "Why did the picture get arrested? It got framed.",
    "Why do M&Ms go to school? Because they want to be a Smartie.",
    "Knock, knock. Who's there? Tank. Tank who? You're welcome.",
    "How do you protect a bagel? Lox it up.",
    "I like telling Dad jokes. Sometimes he laughs.",
    "Why did the stadium get hot after the game? All of the fans left.",
    "Why shouldn't you enter into a contract with Wolverine? Because of his retractable clause.",
    "What kind of coffee does a vampire drink? De-coffin-ated.",
    "How do you keep a skunk from smelling bad? Hold its nose.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "What's the best thing about living in Switzerland? I don't know, but the flag is a big plus.",
    "What's orange and sounds like a parrot? A carrot.",
    "I'm trying to lose weight, but it's a piece of cake!",
    "I'm writing a book about reverse psychology. Please don't buy it.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I got a job at a bakery because I kneaded dough.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "I used to have a fear of hurdles, but I got over it.",
    "What do you call fake spaghetti? An impasta!",
    "I asked the librarian if she had any books on paranoia. She whispered, 'They're right behind you!'",
    "Why don't eggs tell jokes? Because they might crack up!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I was going to tell a time-traveling joke, but you didn't like it.",
    "Why did the bicycle fall over? It was two-tired!",
    "What do you call a bee that can't make up its mind? A maybee!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a boomerang that doesn't come back? A stick!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "What do you call a bear with no teeth? A gummy bear!",
    "I asked the librarian if she had any books on paranoia. She whispered, 'They're right behind you!'",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to have a fear of hurdles, but I got over it!",
    "What do you call fake spaghetti? An impasta!",
    "I was going to tell a time-traveling joke, but you didn't like it.",
    "Why did the bicycle fall over? It was two-tired!",
    "What do you call a bee that can't make up its mind? A maybee!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call a boomerang that doesn't come back? A stick!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "Why don't eggs tell jokes? Because they might crack up!",
  ]
   // const fun = jokesArray[Math.floor(Math.random() * jokesArray.length)];
   //  console.log(fun);
  
  const generateButton = document.getElementById("generateButton");
  const jokeContainer = document.getElementById("jokeContainer");
  
  function clickhere() {
    const fun = jokesArray[Math.floor(Math.random() * jokesArray.length)];
    jokeContainer.textContent = fun;
  }
  
  generateButton.addEventListener("click", clickhere);  